[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_upload.flash_size = 4MB
monitor_speed = 115200

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43
    paulstoffregen/XPT2046_Touchscreen @ ^1.4
    nkolban/ESP32 BLE Arduino @ ^1.0.1
    h2zero/NimBLE-Arduino @ ^1.4.3
    rf24libs/RF24 @ ^1.4.8
    bblanchon/ArduinoJson @ ^6.21.5
    elechouse/ELECHOUSE_CC1101_SRC_DRV @ ^1.0.0
    sui77/rc-switch @ ^2.6.4
    kosme/arduinoFFT @ ^2.0.0
    robtillaart/PCF8574 @ ^0.3.3
    crankyoldgit/IRremoteESP8266 @ ^2.8.6

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
